config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :rooms, only: %i[show create], param: :title
  resources :messages, only: :create do
    member { post :like }
  end
  root "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :message, counter_cache: true
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  has_many :likes, dependent: :destroy
  belongs_to :user
  belongs_to :room

  scope :sorted, -> { order(:id) }

  validates :body, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, -> { sorted }, dependent: :destroy
  belongs_to :user

  before_create { self.title = SecureRandom.hex(3) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :messages, -> { sorted }, dependent: :destroy
  has_many :likes, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @new_message = current_user.messages.build(strong_params)

    if @new_message.save
      room = @new_message.room
      @new_message.broadcast_append_to room, target: "room_#{room.id}_messages", locals: { user: current_user, message: @new_message.decorate }
    end
  end

  def like
    @message = Message.find(params[:id])
    like = @message.likes.find_by(user: current_user)

    if like.present?
      like.destroy
    else
      @message.likes.create(user: current_user)
    end

    room = @message.room

    @message.broadcast_replace_to [current_user, room], target: "message_like_#{@message.id}", partial: "messages/heart", locals: { user: current_user, message: @message.decorate }
    @message.broadcast_replace_to room, target: "message_likes_count_#{@message.id}", partial: "messages/likes_count", locals: { user: current_user, message: @message.decorate }
  end

  private

  def strong_params
    params.require(:message).permit(:body, :room_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def after_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
    @new_room = Room.new
  end

  def show
    @room = Room.find_by!(title: params[:title])
    @messages = MessageDecorator.decorate_collection(@room.messages.includes(:user))
    @new_message = current_user&.messages&.build(room: @room)
  end

  def create
    @new_room = Room.new(user: current_user)

    if @new_room.save
      @new_room.broadcast_append_to :rooms
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChatHotwire</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
<div class="min-h-full">
  <nav class="bg-gray-800">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <a href="/">
              <img class="h-8 w-8" src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg" alt="Workflow">
            </a>
          </div>
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline space-x-4">
              <% if current_user.present? %>
                <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
              <% else %>
                <%= link_to 'Sign in', new_user_session_path, class: 'text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium' %>
                <%= link_to 'Sign up', new_user_registration_path, class: 'text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="md:hidden" id="mobile-menu">
      <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
        <% if current_user.present? %>
          <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
          <%= link_to "Sign up", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
        <% end %>
      </div>
    </div>
  </nav>

  <header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold text-gray-900">
        Chat
      </h1>
    </div>
  </header>
  <main>
    <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <%= yield %>
    </div>
  </main>
</div>
</body>
</html>

app/views/messages/_heart.html.erb
<span id="message_like_<%= message.id %>"><%= message.heart(user) %></span>

app/views/messages/_likes_count.html.erb
<span id="message_likes_count_<%= message.id %>"><%= message.likes_count %></span>

app/views/messages/_message.html.erb
<div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg my-4 py-2 pl-1">
  <div class="flex flex-row">
    <div class="basis-1/12"><%= l(message.created_at, format: :short) %></div>
    <div class="basis-3/12"><%= message.user.email %></div>
    <div class="basis-7/12"><%= message.body %></div>
    <div class="basis-1/12">
      <%= link_to like_message_path(message), data: { "turbo-method": :post } do %>
        <%= render partial: "messages/heart", locals: { user: user, message: message } %>
        <%= render partial: "messages/likes_count", locals: { message: message } %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/_room.html.erb
<%= link_to room.title, room_path(room.title), class: "text-current text-blue-500 mr-4", target: "_blank", rel: "noopener noreferrer" %>

app/views/rooms/index.html.erb
<%= turbo_stream_from :rooms %>

<%= turbo_frame_tag :rooms do %>
  <%= render @rooms %>
<% end %>

<% if current_user.present? %>
  <%= form_with model: @new_room, class: "mt-4" do |f| %>
    <div class="flex flex-row">
      <%= f.submit "Create room", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 cursor-pointer basis-1/12" %>
    </div>
  <% end %>
<% end %>

app/views/rooms/show.html.erb
<%= turbo_stream_from @room %>
<%= turbo_stream_from [current_user, @room] %>

<div class="flex flex-col h-96 justify-between">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8" id="chat-container">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8" id="room_<%= @room.id %>_messages">
      <%= render partial: "messages/message", collection: @messages, locals: { user: current_user } %>
    </div>
  </div>
</div>

<%= form_with model: @new_message, data: { controller: "chat_refresh", action: "turbo:submit-end->chat_refresh#clearInput" } do |f| %>
  <div class="rounded-md shadow-sm -space-y-px">
    <%= f.text_field :body, autofocus: true, required: true, placeholder: "Your text", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
    <%= f.hidden_field :room_id, value: @room.id %>
<% end %>